<#
Script: preserve_stdlib.ps1
Purpose: Non-destructively preserve `.omni` stdlib sources by creating
         `.orig.omni` copies (if missing) and generating lightweight
         stub templates under `omni/stdlib/stubs/` for review.

Run from repository root (PowerShell):
  pwsh -NoProfile -ExecutionPolicy Bypass -File scripts\preserve_stdlib.ps1
#>

$root = Join-Path $PSScriptRoot "..\omni\stdlib"
Write-Host "Scanning: $root"

Get-ChildItem -Path $root -Filter *.omni -Recurse | ForEach-Object {
    $file = $_.FullName
    if ($file -like "*.orig.omni") { return }

    $orig = [System.IO.Path]::ChangeExtension($file, ".orig.omni")
    if (-not (Test-Path $orig)) {
        Copy-Item -Path $file -Destination $orig -Force
        Write-Host "Preserved: $file -> $orig"
    } else {
        Write-Host "Orig exists: $orig"
    }

    $stubsDir = Join-Path $root "stubs"
    if (-not (Test-Path $stubsDir)) { New-Item -ItemType Directory -Path $stubsDir | Out-Null }

    $stubPath = Join-Path $stubsDir $_.Name
    if (-not (Test-Path $stubPath)) {
        $stubHeader = @"
-- PRESERVATION STUB: $($_.Name)
-- Generated by scripts/preserve_stdlib.ps1
-- Review and expand the stub as a minimal parseable placeholder.

-- Original preserved at: $([System.IO.Path]::GetFileName($orig))
"@
        $stubHeader | Out-File -FilePath $stubPath -Encoding utf8
        Write-Host "Generated stub: $stubPath"
    } else {
        Write-Host "Stub already exists: $stubPath"
    }
}

Write-Host "Done. Review ./omni/stdlib/stubs/ for generated templates."
